### ISSUE TITLE
unable to download files with space in file name

### ISSUE THREAD

**Issue by rajnishmishra20** [wlfcolin/file-downloader#3]
Some files with space in their name can not be downloaded. I have tried using Url Encoding but that does not helps. I can download these file using Firefox or Chrome on PC.

**Comment by wlfcolin** [comment]
can you give me the url address and the version of the file-downloader, the url "http://182.254.149.157/ftp/image/shop/product/Kids Addition & Subtraction 1.0.apk" that with space goes right in version 0.3.2.

**Comment by wlfcolin** [comment]
version 0.3.2 has been solved
