### ISSUE TITLE
如果下载完成后，在本地手动删除文件，再次点击下载会失败。

### ISSUE THREAD

**Issue by yoxin** [wlfcolin/file-downloader#7]
解决方法：必须调用FileDownloader.delete()来删除文件。为什么会这样呢？

**Comment by wlfcolin** [comment]
先判断状态，如果是FILE_NOT_EXSIT，那么意味着你只能调用reStart或者delete-->start如果不是这个状态可以调用start，原因是不是所有的FILE_NOT_EXSIT都需要重新下载，有需求可能是遇到FILE_NOT_EXSIT后只删掉（这个选择应该交给用户，开发者可以吞了这个逻辑，具体参考demo），故当文件不存在时自动重新下载没有做在start中
